<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Entidades\0e3nhob5.e5t~" />
    <None Remove="Entidades\EntidadCliente.cs~RF3433bc45.TMP" />
    <None Remove="Entidades\EntidadCliente.cs~RF3465697f.TMP" />
    <None Remove="Entidades\EntidadCliente.cs~RF34f08223.TMP" />
    <None Remove="Interfaces\ICliente.cs~RF33d6d10a.TMP" />
  </ItemGroup>

</Project>
