<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="30serpz4.quf~" />
    <None Remove="Aplicacion\Comandos\ComandoCrearCita.cs~RF57767ab5.TMP" />
    <None Remove="Aplicacion\Comandos\ComandoCrearCita.cs~RF5777100f.TMP" />
    <None Remove="Aplicacion\Comandos\ComandoCrearCita.cs~RF578109e4.TMP" />
    <None Remove="Aplicacion\Comandos\ComandoCrearCliente.cs~RF2f478ba1.TMP" />
    <None Remove="Aplicacion\Comandos\ComandoCrearVehiculo.cs~RF64788a21.TMP" />
    <None Remove="Aplicacion\Comandos\ComandoEditarCliente.cs~RF588fbcc8.TMP" />
    <None Remove="Aplicacion\Comandos\ComandoEditarCliente.cs~RF5890e133.TMP" />
    <None Remove="Aplicacion\Comandos\ComandoEditarEstadoCita.cs~RF6464fd9d.TMP" />
    <None Remove="Aplicacion\Comandos\ComandoEditarEstadoCita.cs~RF6466cb0a.TMP" />
    <None Remove="Aplicacion\Comandos\ComandoEliminarCliente.cs~RF5896aedb.TMP" />
    <None Remove="Aplicacion\Consultas\ConsultarClientePorIdentificacion.cs~RF3450753d.TMP" />
    <None Remove="Aplicacion\Consultas\ConsultarClientePorIdentificacion.cs~RF345403b3.TMP" />
    <None Remove="Aplicacion\Consultas\ConsultarClientePorIdentificacion.cs~RF3455306b.TMP" />
    <None Remove="Aplicacion\DTOs\ClienteDTO.cs~RF3451f39f.TMP" />
    <None Remove="Aplicacion\DTOs\CrearCitaDTO.cs~RF57798584.TMP" />
    <None Remove="Aplicacion\DTOs\CrearVehiculoDTO.cs~RF2f3b4e54.TMP" />
    <None Remove="Aplicacion\DTOs\EditarClienteDTO.cs~RF588b2bf5.TMP" />
    <None Remove="Aplicacion\DTOs\EditarFechaCitaDTO.cs~RF586e5c0b.TMP" />
    <None Remove="Aplicacion\Manejadores\445lttxq.5du~" />
    <None Remove="Aplicacion\Manejadores\ManejadorConsultarCitasPorCliente.cs~RF6444f4ee.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorConsultarClientePorIdentificacion.cs~RF3463ceca.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorCrearCita.cs~RF5878da62.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorCrearCita.cs~RF5915af5f.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorCrearCita.cs~RF591956eb.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorCrearCliente.cs~RF2ecf495f.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorCrearCliente.cs~RF2f4f8a71.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorCrearCliente.cs~RF33d91acb.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorCrearVehiculo.cs~RF359a20bf.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorEditarCita.cs~RF58779c73.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorEditarCita.cs~RF58796ea3.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorEditarCita.cs~RF591e4b0b.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorEditarCliente.cs~RF588de355.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorEditarCliente.cs~RF5894387c.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorEditarCliente.cs~RF59246f9d.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorEditarCliente.cs~RF592fae95.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorEliminarCita.cs~RF5880dd88.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorEliminarCita.cs~RF5923256a.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorEliminarCita.cs~RF5925d642.TMP" />
    <None Remove="Aplicacion\Manejadores\ManejadorEliminarCliente.cs~RF59344b9d.TMP" />
    <None Remove="appsettings.Development.json~RF39f33fab.TMP" />
    <None Remove="appsettings.Development.json~RF39f5d337.TMP" />
    <None Remove="Extensiones\ExtensionCors.cs~RF3ab293a6.TMP" />
    <None Remove="Extensiones\ExtensionCors.cs~RF3ab5d2a4.TMP" />
    <None Remove="Extensiones\ExtensionCors.cs~RF3ab638f0.TMP" />
    <None Remove="Extensiones\ExtensionMediador.cs~RF3a0bb3fc.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TurboCita.Dominio\TurboCita.Dominio.csproj" />
    <ProjectReference Include="..\TurboCita.Infraestructura\TurboCita.Infraestructura.csproj" />
  </ItemGroup>

</Project>
