//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurboCita.Infraestructura.Recursos {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcesosSQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcesosSQL() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TurboCita.Infraestructura.Recursos.ProcesosSQL", typeof(ProcesosSQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Cita (
        ///    ClienteId,
        ///    VehiculoId,
        ///    Estado,
        ///    FechaCita
        ///)
        ///VALUES (
        ///    @clienteId,
        ///    @vehiculoId,
        ///    @estado,
        ///    @fechaCita
        ///);.
        /// </summary>
        internal static string CrearCita {
            get {
                return ResourceManager.GetString("CrearCita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Cliente (
        ///    Nombres,
        ///    Apellidos,
        ///    TipoDocumento,
        ///    NumeroDocumento,
        ///    Direccion,
        ///    CorreoElectronico,
        ///    Celular
        ///)
        ///VALUES (
        ///    @Nombres,
        ///    @Apellidos,
        ///    @TipoDocumento,
        ///    @NumeroDocumento,
        ///    @Direccion,
        ///    @CorreoElectronico,
        ///    @Celular
        ///);
        ///.
        /// </summary>
        internal static string CrearCliente {
            get {
                return ResourceManager.GetString("CrearCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Vehiculo (
        ///    ClienteID,
        ///    TipoVehiculo,
        ///    Placa
        ///)
        ///VALUES (
        ///    @ClienteId,
        ///    @TipoVehiculo,
        ///    @Placa
        ///);.
        /// </summary>
        internal static string CrearVehiculo {
            get {
                return ResourceManager.GetString("CrearVehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE Cliente
        ///SET 
        ///    Direccion = @direccion,
        ///    CorreoElectronico = @correoElectronico,
        ///    Celular = @celular
        ///WHERE ClienteId = @clienteId;.
        /// </summary>
        internal static string EditarCliente {
            get {
                return ResourceManager.GetString("EditarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE Cita
        ///SET Estado = @estado
        ///WHERE CitaId = @citaId;.
        /// </summary>
        internal static string EditarEstadoCita {
            get {
                return ResourceManager.GetString("EditarEstadoCita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a UPDATE Cita
        ///SET FechaCita = @fechaCita
        ///WHERE CitaId = @citaId;.
        /// </summary>
        internal static string EditarFechaCita {
            get {
                return ResourceManager.GetString("EditarFechaCita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE FROM Cita
        ///WHERE CitaId = @citaId;.
        /// </summary>
        internal static string EliminarCita {
            get {
                return ResourceManager.GetString("EliminarCita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DELETE FROM Vehiculo
        ///WHERE ClienteId = @clienteId;
        ///
        ///DELETE FROM Cliente
        ///WHERE ClienteId = @clienteId;.
        /// </summary>
        internal static string EliminarCliente {
            get {
                return ResourceManager.GetString("EliminarCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///    CitaId AS Id,
        ///    ClienteId,
        ///    VehiculoId,
        ///    Estado,
        ///    FechaRegistro,
        ///    FechaCita
        ///FROM Cita
        ///WHERE ClienteId = @clienteId;.
        /// </summary>
        internal static string ObtenerCitasPorClienteId {
            get {
                return ResourceManager.GetString("ObtenerCitasPorClienteId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT ClienteId AS Id, *
        ///FROM Cliente
        ///WHERE TipoDocumento = @tipoDocumento
        ///  AND NumeroDocumento = @numeroDocumento;.
        /// </summary>
        internal static string ObtenerClientePorIdentificacion {
            get {
                return ResourceManager.GetString("ObtenerClientePorIdentificacion", resourceCulture);
            }
        }
    }
}
